name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建和推送 Docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.arc-xpu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whispera770:${{ github.event.release.tag_name }}

      - name: Post build notifications
        run: echo "Docker image has been built and pushed successfully"
